version: '3'

services:

  openldap:
    image: osixia/openldap:latest
    ports:
      - 389:389 # unencrypted
      - 636:636 # over ssl
    environment:
      LDAP_ORGANISATION:    Example
      LDAP_DOMAIN:          example
      LDAP_ADMIN_PASSWORD:  secret
    volumes:
      - openldap-database:/var/lib/ldap
      - openldap-config:/etc/ldap/slapd.d
      - ./example.ldif:/example.ldif

  phpldapadmin:
    image: osixia/phpldapadmin:latest  
    depends_on:
      - openldap
    ports:
      - 8092:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS:  openldap # IP of openldap server
      PHPLDAPADMIN_HTTPS:       'false'

  authdaemon:
    image: nginx-ldap-auth-daemon:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - openldap
    volumes:
      - ./nginx-ldap-auth-daemon.py:/nginx-ldap-auth-daemon.py
    command: [
      "python", "/nginx-ldap-auth-daemon.py",
      "--host", "0.0.0.0",
      "--port", "80"
    ]

  appserver:
    image: python:2-alpine
    environment:
      HOST: 0.0.0.0
      PORT: 80
    volumes:
      - ./backend-sample-app.py:/backend-sample-app.py
    command: [python, /backend-sample-app.py]

  nginx:
    image: nginx:latest
    depends_on:
      - authdaemon
      - appserver
    ports:
      - 8081:80
    volumes:
      - ./nginx-ldap-auth.conf:/etc/nginx/nginx.conf
    command: [nginx, '-g', 'daemon off;']

volumes:
  openldap-database: null
  openldap-config: null
