version: '2.3'

services:

  # openldap:
  #   image: osixia/openldap:latest
  #   ports:
  #     - 389:389 # unencrypted
  #     - 636:636 # over ssl
  #   environment:
  #     LDAP_ORGANISATION:    Example
  #     LDAP_DOMAIN:          example
  #     LDAP_ADMIN_PASSWORD:  secret
  #   volumes:
  #     - openldap-database:/var/lib/ldap
  #     - openldap-config:/etc/ldap/slapd.d
  #     - ./example.ldif:/example.ldif

  # phpldapadmin:
  #   image: osixia/phpldapadmin:latest  
  #   depends_on:
  #     - openldap
  #   ports:
  #     - 8092:80
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS:  openldap # IP of openldap server
  #     PHPLDAPADMIN_HTTPS:       'false'

  postgres:
    image: postgres:11.0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      POSTGRES_DB:        keycloak
      POSTGRES_USER:      keycloak
      POSTGRES_PASSWORD:  password
    volumes:
      - pg-storage:/var/lib/postgresql/data:Z

  keycloak:
    image: jboss/keycloak:latest
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/auth/realms/master"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 8s
    depends_on:
      postgres:
        condition: service_healthy
      # openldap:
      #   condition: service_started
    environment:
      DB_VENDOR:                POSTGRES
      DB_ADDR:                  postgres
      DB_DATABASE:              keycloak
      DB_USER:                  keycloak
      DB_SCHEMA:                public
      DB_PASSWORD:              password
      KEYCLOAK_USER:            admin
      KEYCLOAK_PASSWORD:        secret
      # PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 8080:8080

  appserver:
    image: python:2-alpine
    environment:
      HOST: 0.0.0.0
      PORT: 80
    volumes:
      - ./appserver.py:/appserver.py
    command: [python, /appserver.py]

  nginx:
    image: nginx:1.15.7
    healthcheck:
      test: ["CMD", "/bin/bash", "service nginx status"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
      appserver:
        condition: service_started
    ports:
      - 8081:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
    command: [nginx, '-g', 'daemon off;']

  oauthproxy:
    image: bitnami/oauth2-proxy:latest
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
      nginx:
        condition: service_started
    ports:
      - 4180:4180
    command: [
      "--provider=oidc",
      "--oidc-issuer-url=http://${HOST}:8081/auth/realms/master",
      "--cookie-secure=false",
      "--upstream=http://${HOST}:8081",
      "--http-address=oauthproxy:4180",
      "--redirect-url=http://${HOST}:8081/oauth2/callback",
      "--email-domain=*"
    ]
    environment:
      OAUTH2_PROXY_COOKIE_SECRET: totally-secret-key
      OAUTH2_PROXY_COOKIE_DOMAIN: ${HOST}
      OAUTH2_PROXY_CLIENT_ID:     appserver
      OAUTH2_PROXY_CLIENT_SECRET: 1795d882-300a-4b3c-bce1-1be2d5be7c7a
    
volumes:
  openldap-database: null
  openldap-config: null
  pg-storage: null
