version: '2.3'

services:

  postgres:
    image: postgres:11.0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      POSTGRES_DB:        keycloak
      POSTGRES_USER:      keycloak
      POSTGRES_PASSWORD:  password
    volumes:
      - pg-storage:/var/lib/postgresql/data:Z

  keycloak:
    image: jboss/keycloak:latest
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/auth/realms/master"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 8s
    depends_on:
      postgres:
        condition: service_healthy
      # openldap:
      #   condition: service_started
    environment:
      DB_VENDOR:                POSTGRES
      DB_ADDR:                  postgres
      DB_DATABASE:              keycloak
      DB_USER:                  keycloak
      DB_SCHEMA:                public
      DB_PASSWORD:              password
      KEYCLOAK_USER:            admin
      KEYCLOAK_PASSWORD:        secret
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx-selfsigned.crt:/etc/x509/https/tls.crt
      - ./nginx/nginx-selfsigned.key:/etc/x509/https/tls.key

  appserver:
    image: python:2-alpine
    environment:
      HOST: 0.0.0.0
      PORT: 80
    volumes:
      - ./appserver.py:/appserver.py
    command: [python, /appserver.py]

  gatekeeper:
    image: keycloak/keycloak-gatekeeper
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - ./gatekeeper.yaml:/gatekeeper.yaml:ro
    command: [
      --config,                   "/gatekeeper.yaml",
      --listen,                   "0.0.0.0:3000",
      --upstream-url,             "https://${HOST}",
      # --discovery-url,            "http://keycloak:8080/auth/realms/master",
      --discovery-url,            "https://${HOST}/auth/realms/master",
      --redirection-url,          "https://${HOST}",
      --client-id,                appserver,
      --client-secret,            d7bed7f9-73d9-4125-ace3-8493bcede8aa,
      --skip-upstream-tls-verify, "true"
    ]

  nginx:
    image: nginx:1.15.7
    healthcheck:
      test: ["CMD", "/bin/bash", "service nginx status"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
      appserver:
        condition: service_started
      gatekeeper:
        condition: service_started
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./nginx/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./nginx/snippets:/etc/nginx/snippets
    command: [nginx, '-g', 'daemon off;']

volumes:
  openldap-database: null
  openldap-config: null
  pg-storage: null
